/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TPKS;

import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author Anna
 */
public class Mini extends javax.swing.JFrame {

    /**
     * Constructor
     */
    public Mini() {
        initComponents();
    }

    /**
     * Constructor
     *
     * @param minis minimizations
     * @param ddnfs ddnf forms
     * @param functions names of functions
     */
    public Mini(ArrayList<ArrayList<char[]>> minis, ArrayList<ArrayList<char[]>> ddnfs, ArrayList<String> functions) {
        initComponents();
        for (int i = 0; i < functions.size(); i++) {
            String buf = functions.get(i) + " = ";
            for (int k = 0; k < ddnfs.get(i).size(); k++) {
                for (int j = 0; j < ddnfs.get(i).get(k).length; j++) {
                    buf = buf + ddnfs.get(i).get(k)[j];
                }
                buf = buf + " v ";
            }
            buf = buf + " = ";
            for (int k = 0; k < minis.get(i).size(); k++) {
                for (int j = 0; j < minis.get(i).get(k).length; j++) {
                    buf = buf + minis.get(i).get(k)[j];
                }
                buf = buf + " v ";
            }
            jTextArea1.setText(jTextArea1.getText() + "\r\n" + buf);
        }

    }
//get and set text to text area

    public String getText() {
        return jTextArea1.getText();
    }

    public void setText(String str) {
        jTextArea1.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
