/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TPKS;

import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import TPKS.Table;

/**
 *
 * @author Anna
 */
public class TableFrame extends javax.swing.JFrame {

    /**
     * Constructor
     *
     * @param mTable table
     */
    public TableFrame(Table mTable) {
        table = mTable.getTabl();
        colums = mTable.getColums();
        rows = mTable.getRows();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new Model());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Model of table
     */
    private class Model implements TableModel {

        @Override
        public int getRowCount() {
            return rows.length;
        }

        @Override
        public int getColumnCount() {
            return colums.length;
        }

        @Override
        public String getColumnName(int i) {
            return colums[i];
        }

        @Override
        public Class<?> getColumnClass(int i) {
            return String.class;
        }

        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }

        @Override
        public Object getValueAt(int i, int j) {
            if (j == 0) {
                return rows[i];
            } else {
                return table[i][j - 1];
            }
        }

        @Override
        public void setValueAt(Object o, int i, int i1) {
        }

        @Override
        public void addTableModelListener(TableModelListener tl) {
        }

        @Override
        public void removeTableModelListener(TableModelListener tl) {
        }
    }
    //Variables
    private char[][] table;
    private String[] colums;
    private String[] rows;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
